iv-org/invidious-companion

src/routes/health.ts
src/routes/index.ts

add health endpoint for healthchecks

---

.github/workflows/deno-check.yaml
.github/workflows/deno.yaml

This should help ensure that PRs are properly linted.
I tested this on my own repository here:
https://github.com/ChunkyProgrammer/invidious-companion/actions/runs/12542250314/job/34971807291?pr=1
I commented out the `deno fmt --check` step for now so it wouldn't conflict/fail for the already opened PRs

Add deno.yaml to lint PRs

---

config/default.toml
src/lib/helpers/getFetchClient.ts
src/routes/videoPlaybackProxy.ts

I made this PR to deal with an issue I was having. When using Dash on longer videos, occasionally a request to Youtube would hang. Eventually my reverse proxy would time out (about a minute) and the frontend would get a 504. It didn't retry, so the video just went to a loading animation and wouldn't work again unless the page was reloaded.
In order to resolve this, I've added a timeout to googlevideo requests, and set them to retry 5 times. So far I've had this happen 4 or 5 times in 1.5 hours of a video, and they are always succeeding on the second request. I don't have any failures with this patch.
The core of this issue may be something unreliable in my network. I'm working on resolving that, but this PR makes the companion more resilient to connections not being perfect. The …

feat: timeout and retry fetches in proxy

---

src/lib/types/HonoVariables.ts
src/main.ts
src/routes/invidious_routes/dashManifest.ts
src/routes/invidious_routes/latestVersion.ts
src/routes/videoPlaybackProxy.ts
src/routes/youtube_api_routes/player.ts

Hono context variables can be typed by setting ContextVariableMap in the 'hono' module. This allows the type-checks to be cleaner and simpler, and to not require ts overrides
c.get also isn't async, so doesn't need to be awaited

Chore: Clean up Hono types

---

Dockerfile
src/main.ts

Replaces https://github.com/iv-org/invidious-companion/pull/48 due to https://github.com/iv-org/invidious-companion/issues/24#issuecomment-2677141666

dockerfile: replace built-in healthcheck with tiny-health-checker for container healthchecks

---

src/routes/invidious_routes/dashManifest.ts

`c.text` sets the Content-Type to `text/plain; charset=UTF-8` regardless of the value set by `c.header()`. Using c.body prevents that from happening.

fix: Replace c.text by c.body to prevent Content-Type header being rewriten

---

config/default.toml
src/lib/helpers/youtubePlayerHandling.ts

Remove the usage of base_url in companion since like @Fijxu said, invidious has this info now through "public_url": https://github.com/iv-org/invidious/pull/4985#issuecomment-2692940672

chore: remove base_url sending

---

deno.json
deno.lock
src/lib/helpers/youtubePlayerHandling.ts
src/lib/helpers/youtubePlayerReq.ts
src/lib/jobs/potoken.ts
src/lib/types/HonoVariables.ts
src/main.ts
src/routes/invidious_routes/captions.ts
src/routes/invidious_routes/dashManifest.ts
src/routes/invidious_routes/latestVersion.ts
src/routes/youtube_api_routes/player.ts

Adds initial support for the content PO token functionality provided by BGUtils, using https://github.com/LuanRT/BgUtils/blob/main/examples/node/innertube-challenge-fetcher-example.ts as the base. 
TO CHECK:
~~1. ongoing playback after tokens rotate~~
~~2. caching vs non-caching setups both work~~
~~3. livestreams etc~~ _not really relevant as HLS livestreams dont go through companion_
4. logged in? non-web clients? _Not sure whether there's anything that needs to be checked here. Does companion support being logged-in with a youtube account at the moment?_
~~TO FIX:~~
~~1. deno compile isn't working right now. Something new in the way the BotGuard challenge works means it now needs Canvas installed for JSDom - a call to `getContext` triggers this. It can be tested with `deno run dev`.~~ …

support for Content PO Token using BGUtils, and PO token checks using real videos

---

deno.json
deno.lock
src/lib/helpers/getFetchClient.ts
src/lib/helpers/konfigLoader.ts
src/lib/helpers/verifyRequest.ts
src/lib/helpers/youtubePlayerHandling.ts
src/main.ts

- Move all the imported URLs to deno.json
- Easier for updating: only need to look into deno.json
- Update the version of the libs.
- Remove the duplicated "hono" from deno.json
- Remove `^` from the version because it means that we were not using a fixed version.

chore: move everything to deno.json + update libs

---

src/lib/helpers/config.ts

Changing from strict 16 characters only to minimum 16 characters.
The lib that we use just cut after 16 characters, so we can allow people to set more than 16 characters if they really want. And on the invidious side, we only check if it's more than 16 characters:
https://github.com/iv-org/invidious/blob/409d12a81e75451a8efc7574d4bad622f75d3769/src/invidious/config.cr#L270-L272

chore: check length minimum 16

---

src/lib/helpers/config.ts

Changes an error message referencing local.toml to just refer generically to "your configuration"

chore: change error message referencing local.toml

---

src/lib/helpers/encodeRFC5987ValueChars.ts
src/routes/index.ts
src/routes/invidious_routes/download.ts
src/routes/invidious_routes/latestVersion.ts
src/routes/videoPlaybackProxy.ts

This PR adds support for Invidious's download endpoint to companion.
Closes #13

Add Invidious's download endpoint

---

config/config.example.toml
src/lib/helpers/config.ts
src/lib/helpers/encryptQuery.ts
src/routes/invidious_routes/dashManifest.ts
src/routes/invidious_routes/latestVersion.ts
src/routes/videoPlaybackProxy.ts

Closes #29
Requires support in Invidious if videoplayback is going to be proxied trough Invidious, but that doesn't make that much sense since companion already does that. Same thing applies to [piped-proxy](https://github.com/TeamPiped/piped-proxy)

feat: add support for encrypted query parameters

---

src/routes/invidious_routes/dashManifest.ts

as mentioned on https://github.com/iv-org/invidious-companion/issues/78
I can't see any breakages with the current videojs player on firefox or chrome with videos that have both av01 and avc1 codecs delivered. 
I've kept it filtering to MP4 and non-video elements.
This is working well on browser, clipious on mobile and clipious on android TV.

fix: remove av01 specific filtering and just filter to non-video and mp4 video

---

src/routes/videoPlaybackProxy.ts

While checking the videoplayback proxy from Invidious: https://github.com/iv-org/invidious/blob/23ff6135bb4304c6b5e9de6fc06e67bfadc9651a/src/invidious/routes/video_playback.cr#L247-L252
I saw that we are not responding to the possible OPTIONS request for CORS preflight: https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request
This seems to be important for all Firefox and Chrome version. Without that, the playback fails.

chore: add options http method for videoplaybackproxy

---

src/lib/helpers/config.ts
src/lib/helpers/youtubePlayerHandling.ts
src/lib/helpers/youtubePlayerReq.ts
src/lib/jobs/potoken.ts
src/lib/jobs/worker.ts
src/lib/types/HonoVariables.ts
src/main.ts

Sets up an alternate approach to PO token generation where all of the dirty work (JSDOM, BotGuard handling etc) is put into a Web Worker. This allows us to terminate the web worker when a new PO token has been generated, helping to keep memory leaks in check. 
This isn't a perfect diagram, but it kind of gives you the sequence of events.
```mermaid
sequenceDiagram
participant main as main.ts
participant job as potoken.ts
participant worker as [NEW] worker.ts
participant old_worker as [PREVIOUS] worker.ts
participant youtube as YouTube/BotGuard
main->>job: Get new Tokens
job->>worker: Spawn
worker->>job: Ready
job->>worker: Initialise (Pass config)
worker->>youtube: generate valid token
worker->>job: Initialised, ready to generate content tokens
job->>job: Find video to check token against …
```

Move po token to webworker

---

config/config.example.toml
deno.json
deno.lock
grafana_dashboard.json
src/lib/helpers/config.ts
src/lib/helpers/metrics.ts
src/lib/helpers/youtubePlayerHandling.ts
src/lib/jobs/potoken.ts
src/lib/types/HonoVariables.ts
src/main.ts
src/routes/index.ts
src/routes/invidious_routes/captions.ts
src/routes/invidious_routes/dashManifest.ts
src/routes/invidious_routes/latestVersion.ts
src/routes/metrics.ts
src/routes/youtube_api_routes/player.ts

Useful for troubleshooting blockages in a visual manner using Grafana.
It doesn't count how many times `poTokenGenerate` has failed between lines 69-83, I didn't wanted to touch that much code. But I'll make a new commit to count on those lines too so you can review it.

add support for prometheus metrics

---

src/lib/jobs/potoken.ts
src/routes/videoPlaybackProxy.ts

This should hopefully fix playback of the medium quality in iOS Safari, as it now only returns that the length is unknown when it is actually unknown.
Unlike desktop Firefox which requests the entire file with the range `0-`, iOS Safari uses partial requests, for which Invidious companion currently returns an unknown content length.
I haven't actually installed deno and tested if this fully fixes the problem but I have confirmed that the `clen` query parameter does exist for the medium quality on the `inv.nadeko.net` instance and just in case that query parameter is missing it will fallback to returning the `*` for unknown.

fix: Fix content-range header in video proxy for partial requests

---

Dockerfile

Latest version is 2.2.8 but I prefer to update it to 2.2.5 since is the latest Deno version that I used on prod

ci: update deno to 2.2.10

---

src/lib/helpers/youtubePlayerReq.ts

Should help with https://github.com/iv-org/invidious-companion/issues/60
When no adaptive formats are found, we try with other youtube clients.
If that worked, then we merge the youtube response from WEB client with the other client for only the adaptive formats URLs.
We try "MWEB" and "TVHTML5".

fallback to other youtube clients in case of no adaptive formats (dash)

---

config/config.example.toml
src/lib/helpers/config.ts

sets the default timeout to 30 seconds. This was causing issues because Deno doesn't ever close connections automatically.

chore: sets a default timeout of 30 seconds on requests

---

config/config.example.toml

Update the comment in the example config to show that only secrets of exactly 16 characters are accepted, as discussed in #81.
This pull request partially fixes #122.

Reflect secret key character limit in example config comment

---

src/lib/helpers/youtubePlayerReq.ts

MWEB does not have multiple audios, where as TVHTML5 has. Switching the order of fallback retries.

Fallback to TV yt client then MWEB

---

src/lib/helpers/youtubePlayerReq.ts

Works well on the MWEB client (forcing it with `client_type: ClientType.MWEB,` on each `Innertube.create` for testing) and TV client (forcing the `client` on `watch_endpoint` to `"TV"` for testing).
I wasn't able to test with a recently uploaded video (which are the ones without DASH urls), but they should work.
Fixes: https://github.com/iv-org/invidious-companion/issues/51
Thanks to @absidue on https://github.com/iv-org/invidious-companion/issues/51#issuecomment-2780557907

feat: support for sensitive content videos

---

src/lib/helpers/youtubePlayerHandling.ts

Closes https://github.com/iv-org/invidious-companion/issues/136
This is what Invidious sees:
```
{
"responseContext": {
"serviceTrackingParams": [
{
"service": "GFEEDBACK",
"params": [
{
"key": "is_viewed_live",
"value": "False"
},
{
"key": "wh_paused",
"value": "0"
},
{
"key": "logged_in",
"value": "0"
},
{
"key": "e",
"value": "[REDACTED]"
},
{
"key": "visitor_data",
"value": "Cgs2dmxMRS1DcnpoWSi1_7fBBjIKCgJDTBIEGgAgZQ%3D%3D"
}
]
},
{
"service": "CSI",
"params": [
{
"key": "c",
"value": "WEB"
},
{
"key": "cver",
"value": "2.20250222.10.00"
},
{
"key": "yt_li",
"value": "0"
},
{
"key": "GetPlayer_rid",
"value": "0x0d11d9b74525888e"
}
]
},
{
"service": "GUIDED_HELP",
"params": [
{
"key": "logged_in",
"value": "0"
}
]
},
{
"service": "ECATCHER",
"params": [
{
"key": "client.version", …
```

Return error to Invidious if `playabilityStatus.status` is `ERROR`

---

src/lib/jobs/worker.ts

I've noticed the issue while trying to set up a proxy.
Proxy was not being used for innertubeClient.getAttestationChallenge call, and server could not start.
Just using the configured fetchImpl fixed the issue for me.
Fixes https://github.com/iv-org/invidious-companion/issues/165

Pass inner fetch function implementation to worker local Innertube client

---

Dockerfile
config/config.example.toml
src/lib/helpers/config.ts
src/main.ts
src/routes/index.ts
src/routes/invidious_routes/captions.ts
src/routes/invidious_routes/dashManifest.ts
src/routes/invidious_routes/download.ts
src/routes/invidious_routes/latestVersion.ts
src/tests/main_test.ts

fixes #118 
linked to https://github.com/iv-org/invidious/pull/5266
This commit set the default base_path to `/companion`. The benefits are:
- one route for all things about companion, easier for configuring the reverse proxy. less error-prone.
- will be easier to implement `proxy the requests from invidious to companion if public_url is not configured. In order to avoid having to touch the reverse proxy.` from https://github.com/iv-org/invidious/issues/5215  
because there will only need one route to create in invidious instead of multiples one (/latest_version and so on)
- since all the paths will be under one route, we can add easily new paths without asking the user to update their reverse proxy
The big downside:
- This will set the default base_path to /companion, so all current …

set default base_path hono /companion + allow to customize it

---

src/main.ts
src/routes/index.ts

In https://github.com/iv-org/invidious-companion/commit/25f1b1980736d70c92ba4815cda200569ad91921, the `/metrics` route got moved to `/companion/metrics`, I assume this was not an intended change, so I did this to keep routes unrelated to Youtube requests more organized

Refactor hono routes
